inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'perf/**/*'
    - 'spec/shared/lib/mrss/**/*'
    - 'test-apps/**/*'
    - 'vendor/**/*'

Style/Documentation:
  AllowedConstants: ['ClassMethods']
  Exclude:
    - 'gemfiles/**/*'
    - 'spec/**/*'

Style/DocumentationMethod:
  Exclude:
    - 'gemfiles/**/*'
    - 'spec/**/*'

# --------------------------------------------------
# These cops are having CI issues. Enable later.

Performance/StringInclude:
  Enabled: false

# --------------------------------------------------
# Specific files skipped. These can be inlined later.

Layout/LineContinuationLeadingSpace:
  Exclude:
    - 'spec/integration/app_spec.rb'

Lint/RedundantCopDisableDirective:
  Exclude:
    - 'spec/mongoid/version_spec.rb'

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/support/constraints.rb'

Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - 'spec/mongoid/equality_spec.rb'

# --------------------------------------------------
# Cops below this line are intentionally disabled.

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# Mongoid behavior differs from ActiveRecord
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false
