inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'perf/**/*'
    - 'spec/shared/lib/mrss/**/*'
    - 'test-apps/**/*'
    - 'vendor/**/*'

Gemspec:
  Enabled: true

# -----------------------------------
# TODO: Enable and fix the cops below
# -----------------------------------

Layout:
  Enabled: false

Lint:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Performance:
  Enabled: false

Rake:
  Enabled: false

Rails:
  Enabled: false

RSpec:
  Enabled: false

Security:
  Exclude:
    - 'spec/**/*'

Style:
  Enabled: false

Style/Documentation:
  Enabled: true
  AllowedConstants: ['ClassMethods']
  Exclude:
    - 'gemfiles/**/*'
    - 'spec/**/*'

Style/DocumentationMethod:
  Enabled: true
  Exclude:
    - 'gemfiles/**/*'
    - 'spec/**/*'

# --------------------------------------
# Cops below this line set intentionally
# --------------------------------------

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

# Not used by Mongoid
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false
