inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'perf/**/*'
    - 'test-apps/**/*'
    - 'vendor/**/*'

Lint/EmptyClass:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  AllowedConstants: ['ClassMethods']
  Exclude:
    - 'gemfiles/**/*'
    - 'spec/**/*'

Style/DocumentationMethod:
  Exclude:
    - 'gemfiles/**/*'
    - 'spec/**/*'

# --------------------------------------------------
# These cops are having CI issues. Enable later.

Performance/StringInclude:
  Enabled: false

Performance/RegexpMatch:
  Exclude:
    - 'Gemfile'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'

# --------------------------------------------------
# Cops with specific files skipped. These can be inlined later.

Layout/LineContinuationLeadingSpace:
  Exclude:
    - 'spec/integration/app_spec.rb'

Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*'

Lint/RedundantCopDisableDirective:
  Exclude:
    - 'spec/mongoid/version_spec.rb'

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/support/constraints.rb'

Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - 'spec/mongoid/equality_spec.rb'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

RSpec/AroundBlock:
  Exclude:
    - 'spec/support/constraints.rb'

RSpec/IdenticalEqualityAssertion:
  Exclude:
    - 'spec/mongoid/equality_spec.rb'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/integration/callbacks_spec.rb'

Security/MarshalLoad:
  Exclude:
    - 'spec/mongoid/criteria/marshalable_spec.rb'

RSpec/SubjectStub:
  Exclude:
    - 'spec/mongoid/collection_configurable_spec.rb'

# --------------------------------------------------
# These cops are disabled by default, but should be periodically
# checked and cleaned up.

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# --------------------------------------------------
# These cops are intentionally disabled due to incompatibility.

# Mongoid behavior differs from ActiveRecord
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

# False positives
Lint/HashCompareByIdentity:
  Exclude:
    - 'lib/mongoid/persistence_context.rb'
    - 'lib/mongoid/threaded.rb'

# --------------------------------------------------
# These cops are intentionally configured due to style preference.

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/mongoid/association/referenced/has_many/proxy_spec.rb'
    - 'spec/mongoid/interceptable_spec.rb'
    - 'spec/mongoid/touchable_spec.rb'

Lint/MissingSuper:
  Exclude:
    - 'lib/mongoid/association/embedded/embedded_in/proxy.rb'
    - 'lib/mongoid/association/embedded/embeds_many/proxy.rb'
    - 'lib/mongoid/association/embedded/embeds_one/proxy.rb'
    - 'lib/mongoid/association/referenced/belongs_to/proxy.rb'
    - 'lib/mongoid/association/referenced/has_many/proxy.rb'
    - 'lib/mongoid/association/referenced/has_one/proxy.rb'
    - 'lib/mongoid/criteria/queryable/pipeline.rb'
    - 'lib/mongoid/criteria/queryable/smash.rb'

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/FetchEnvVar:
  Enabled: false

Style/GuardClause:
  AllowConsecutiveConditionals: true
  Exclude:
    - 'Gemfile'
    - 'gemfiles/**/*'

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

# See: https://github.com/rubocop/rubocop/issues/11798
# Enforce multiline style if it becomes available in the future.
Style/WhileUntilModifier:
  Enabled: false

# See: https://github.com/rubocop/rubocop/issues/11802
Style/SymbolArray:
  Exclude:
    - 'spec/mongoid/criteria/queryable/selector_spec.rb'
    - 'spec/mongoid/criteria/queryable/options_spec.rb'
