# frozen_string_literal: true

require 'active_document/extensions/array'
require 'active_document/extensions/big_decimal'
require 'active_document/extensions/binary'
require 'active_document/extensions/boolean'
require 'active_document/extensions/date'
require 'active_document/extensions/date_time'
require 'active_document/extensions/decimal128'
require 'active_document/extensions/false_class'
require 'active_document/extensions/float'
require 'active_document/extensions/hash'
require 'active_document/extensions/integer'
require 'active_document/extensions/module'
require 'active_document/extensions/nil_class'
require 'active_document/extensions/object'
require 'active_document/extensions/object_id'
require 'active_document/extensions/range'
require 'active_document/extensions/raw_value'
require 'active_document/extensions/regexp'
require 'active_document/extensions/set'
require 'active_document/extensions/string'
require 'active_document/stringified_symbol'
require 'active_document/extensions/symbol'
require 'active_document/extensions/time'
require 'active_document/extensions/time_with_zone'
require 'active_document/extensions/true_class'
