---
name: Tests

'on':
  - push
  - pull_request

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      CI: true
      TESTOPTS: '-v'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop --parallel

  test:
    name: "${{matrix.ruby}}
      rails:${{matrix.rails}}
      mongodb:${{matrix.mongodb || '8.0'}}
      fle:${{matrix.fle && 'fle=' || ''}}${{matrix.fle || ''}}
      top:${{matrix.topology || 'server'}}
      os:${{matrix.os || 'ubuntu-20.04'}}"
    env:
      CI: true
      TESTOPTS: '-v'
    runs-on: ${{matrix.os || 'ubuntu-latest'}}
    continue-on-error: "${{matrix.experimental || false}}"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby-3.1
          - ruby-3.2
          - ruby-3.3
          - ruby-3.4
        os:
          - ubuntu-latest
        topology:
          - server
          - replica_set
          - sharded_cluster
        include:
          # Rails versions
          - ruby: ruby-3.1
            rails: '6.1'
            gemfile: gemfiles/rails_6.1.gemfile
          - ruby: ruby-3.4
            rails: '7.0'
            gemfile: gemfiles/rails_7.0.gemfile
          - ruby: ruby-3.4
            rails: '7.1'
            gemfile: gemfiles/rails_7.1.gemfile
          - ruby: ruby-3.4
            rails: '7.2'
            gemfile: gemfiles/rails_7.2.gemfile
          - ruby: ruby-3.4
            rails: '8.0'
            gemfile: gemfiles/rails_8.0.gemfile

          # TODO: Test driver versions
          # TODO: Test BSON versions

          # Older MongoDB Server versions
          - ruby: ruby-3.4
            mongodb: '6.0'
          - ruby: ruby-3.4
            mongodb: '7.0.19'

          # JRuby
          - ruby: jruby-9.4
            gemfile: gemfiles/rails_7.2.gemfile

          # Field-Level Encryption
          # TODO: support LIBMONGOCRYPT via path
          - ruby: ruby-3.4
            topology: sharded_cluster
            fle: helper
          - ruby: ruby-3.4
            topology: replica_set
            fle: helper
          - ruby: ruby-3.4
            topology: server
            fle: helper
    steps:
      - name: repo checkout
        uses: actions/checkout@v3
      - id: start-mongodb
        name: start mongodb
        uses: mongodb-labs/drivers-evergreen-tools@master
        with:
          version: "${{matrix.mongodb || '8.0'}}"
          topology: "${{matrix.topology || 'replica_set'}}"
      - name: load ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GEMFILE: "${{matrix.gemfile || 'Gemfile'}}"
          FLE: "${{matrix.fle || ''}}"
        with:
          ruby-version: "${{matrix.ruby}}"
          bundler: 2
      - name: bundle
        run: bundle install --jobs 4 --retry 3
        env:
          BUNDLE_GEMFILE: "${{matrix.gemfile || 'Gemfile'}}"
          FLE: "${{matrix.fle || ''}}"
      - name: test
        timeout-minutes: 60
        continue-on-error: "${{matrix.experimental || false}}"
        run: bundle exec rake spec
        env:
          BUNDLE_GEMFILE: "${{matrix.gemfile || 'Gemfile'}}"
          FLE: "${{matrix.fle || ''}}"
          MONGODB_URI: "${{steps.start-mongodb.outputs.cluster-uri}}"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
